language: python
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements.txt
# command to run tests, e.g. python setup.py test
script:  python test/test_fsl_export.py 
# Update subtree nidm from main nidm repository
before_install: 
 - git config --global user.name "TravisCI"
 # Create subtree nidm from main nidm repository
 - git remote add nidm https://github.com/cmaumet/nidm.git
 - git fetch nidm
 - git subtree add --prefix nidm nidm/fsl_gt --squash